### ISSUE TITLE
pretrain does not work

### ISSUE THREAD

**Issue by ergo-zyh** [j96w/GenTP#1]
Hi
The script command mentioned in the README does not work.
_python gentp/scripts/pretrain_rep.py_

`Traceback (most recent call last):
  File "gentp/scripts/pretrain_rep.py", line 128, in <module>
    main()
  File "gentp/scripts/pretrain_rep.py", line 119, in main
    pretrain(model, data_pre_train, optimizer, True)
  File "gentp/scripts/pretrain_rep.py", line 35, in pretrain
    output_syb, output_view, output_seg = model.forward_pre(rgb, seg, syb)
  File "/home/zyh/projects/GenTP/gentp/lib/model.py", line 577, in forward_pre
    feat, _ = self.encoder(rgb, seg)
  File "/home/zyh/anaconda3/envs/skill_learning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zyh/projects/GenTP/gentp/lib/model.py", line 164, in forward
    x_img, x_early_img = self.img_encoder(x_img)
  File "/home/zyh/anaconda3/envs/skill_learning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zyh/anaconda3/envs/skill_learning/lib/python3.8/site-packages/torchvision/models/resnet.py", line 249, in forward
    return self._forward_impl(x)
  File "/home/zyh/anaconda3/envs/skill_learning/lib/python3.8/site-packages/torchvision/models/resnet.py", line 232, in _forward_impl
    x = self.conv1(x)
  File "/home/zyh/anaconda3/envs/skill_learning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zyh/anaconda3/envs/skill_learning/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/zyh/anaconda3/envs/skill_learning/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 439, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[160, 6, 128, 128] to have 3 channels, but got 6 channels instead`

Is the version of torchvision package I pip install wrong? Any help will be useful.

Thanks & Regards.
Ergo

**Comment by j96w** [comment]
Thanks for mentioning this bug. So the input is a combination of rgb+seg so it will be 6 channel. Try to modify the resnet18 encoder's first layer to 6 channel input. Try something like this: `resnet.conv1 = nn.Conv2d(6, 64, kernel_size=7, stride=2, padding=3, bias=False)` after this line https://github.com/j96w/GenTP/blob/main/gentp/lib/model.py#L127

**Comment by ergo-zyh** [comment]
Thanks for your answer, I will try it again.

**Comment by ergo-zyh** [comment]
sorry. After I add the code to modify the resnet18 encoder's first layer, I find another bug.
Traceback (most recent call last):
  File "gentp/scripts/pretrain_rep.py", line 128, in <module>
    main()
  File "gentp/scripts/pretrain_rep.py", line 119, in main
    pretrain(model, data_pre_train, optimizer, True)
  File "gentp/scripts/pretrain_rep.py", line 35, in pretrain
    output_syb, output_view, output_seg = model.forward_pre(rgb, seg, syb)
  File "/home/zyh/projects/GenTP/gentp/lib/model.py", line 575, in forward_pre
    feat, _ = self.encoder(rgb, seg)
  File "/home/zyh/anaconda3/envs/gentp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zyh/projects/GenTP/gentp/lib/model.py", line 163, in forward
    x_img, x_early_img = self.img_encoder(x_img)
ValueError: too many values to unpack (expected 2)

Is the correct code you run or you succeed? Any help will be useful.

Thanks & Regards.
Ergo

**Comment by LikforD** [comment]
@ergo-zyh 

Hello, I'm sorry to bother you. May I ask if you have successfully run and reproduced the code related to GenTP?

Looking forward to your reply.Any help will be useful.
Thanks & Regards.

**Comment by LikforD** [comment]
您好，打扰您了。我想请问一下，关于GenTP的代码您运行成功了吗？或者上面您发现的问题成功解决了吗？
 @希望您能回复！祝好！ @ergo-zyh

**Comment by ergo-zyh** [comment]
Hello, sorry, I forget to see this issue. I have successfully run the code.

**Comment by LikforD** [comment]
@ergo-zyh 
Hello, thank you very much for responding to my message!

 I encountered the same error as when you were debugging the code before: `ValueError: too many values to unpack (expected 2)`.

Can you tell me how you resolved it? I really hope to get your help! Best wishes!
